name: "Full Stack Install Test"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # At 07:00 UTC everyday.
    - cron: "0 7 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  perses-install-check:
    name: Test on ${{ matrix.OS }}-latest, Python ${{ matrix.python-version }}, Perses ${{ matrix.perses-version }}, openMM ${{ matrix.openmm-version }}, openmmtools ${{ matrix.openmmtools-version }}
    runs-on: ${{ matrix.OS }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos']
        python-version:
          - 3.8
          - 3.9
        perses-version:
          - 0.10.1
        openmm-version:
          - 8.2.0
        openmmtools-version:
          - 0.24.4

    steps:
      - uses: actions/checkout@v3

      - name: Setup micromamba env
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-downloads: true
          cache-environment: false

      - name: Install perses
        run:  micromamba install -c jaimergp/label/unsupported-cudatoolkit-shim -c conda-forge perses=${{ matrix.perses-version }} python=${{ matrix.python-version }} openmm=${{ matrix.openmm-version }} openmmtools=${{ matrix.openmmtools-version }}
