name: "Openeye License Check"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # At 07:00 UTC on Monday and Thursday.
    - cron: "0 7 * * 1,4"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  openeye-license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup conda env
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          environment-file: false
          channels: openeye

      - name: Install OpenEye tools
        run:  mamba install openeye-toolkits

      - name: Check Openeye License
        env:
          OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
        run: |
          echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}
          python -c "import openeye; assert openeye.oechem.OEChemIsLicensed(), 'OpenEye license checks failed!'"
